defualt: client
client:
	g++ .\client-example.cpp -o .\client.exe -lws2_32
client-debug:
	g++ .\client-example.cpp -o .\client.exe -lws2_32 -g3
server:
	g++ .\echoServerExample.cpp -o .\server.exe -lws2_32